### ISSUE TITLE
Backport fix for crash in `DatabaseIntrospection.get_table_description()` to Django 3.2.x

### ISSUE THREAD

**Issue by mikevendelux** [Snowflake-Labs/django-snowflake#87]
I'm running 3.2.latest, and when attempting to use `inspectdb` to update model definitions I'm getting the `ValueError: too many values to unpack (expected 11)` error as in #84 because it's expecting an 11-tuple rather than the new 12-tuple.

Django 3.2.x is LTS until ~the end of this quarter~April: https://www.djangoproject.com/download/#supported-versions

Could the 4.x/5.x fix for this please be backported to 3.2.x?

**Comment by timgraham** [comment]
I don't typically update older versions after a new LTS is available (e.g. 3.2.x wouldn't get fixes after 4.2.x is released), but I've made an exception because of this and a data loss issue after a recent Snowflake behavior change (#90).

django-snowflake 3.2, 4.0, and 4.1 are now available on PyPI to fix these issues (as well as 4.2.2 and 5.0.2 which fix the data loss issue).

**Comment by mikevendelux** [comment]
Great, thank you!
